// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'superSecretApiKey-DO-NOT-PUSH-TO-GIT-REPO',
    appId: 'platform:specific:appId',
    messagingSenderId: 'myMessagingSenderId',
    projectId: 'bingio-flutter',
    authDomain: 'bingio-flutter.firebaseapp.com',
    storageBucket: 'bingio-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'superSecretApiKey-DO-NOT-PUSH-TO-GIT-REPO',
    appId: 'platform:specific:appId',
    messagingSenderId: 'myMessagingSenderId',
    projectId: 'bingio-flutter',
    storageBucket: 'bingio-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'superSecretApiKey-DO-NOT-PUSH-TO-GIT-REPO',
    appId: 'platform:specific:appId',
    messagingSenderId: 'myMessagingSenderId',
    projectId: 'bingio-flutter',
    storageBucket: 'bingio-flutter.firebasestorage.app',
    iosBundleId: 'com.dalbrar.bingio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'superSecretApiKey-DO-NOT-PUSH-TO-GIT-REPO',
    appId: 'platform:specific:appId',
    messagingSenderId: 'myMessagingSenderId',
    projectId: 'bingio-flutter',
    storageBucket: 'bingio-flutter.firebasestorage.app',
    iosBundleId: 'com.dalbrar.bingio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'superSecretApiKey-DO-NOT-PUSH-TO-GIT-REPO',
    appId: 'platform:specific:appId',
    messagingSenderId: 'myMessagingSenderId',
    projectId: 'bingio-flutter',
    authDomain: 'bingio-flutter.firebaseapp.com',
    storageBucket: 'bingio-flutter.firebasestorage.app',
  );

}