// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:bingio/secrets/secrets.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: GoogleFirebaseApiKeys.web,
    appId: '1:224930641005:web:ef91e421d15ab21d1afb64',
    messagingSenderId: '224930641005',
    projectId: 'bingio-flutter',
    authDomain: 'bingio-flutter.firebaseapp.com',
    storageBucket: 'bingio-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: GoogleFirebaseApiKeys.android,
    appId: '1:224930641005:android:bb93ead542e278731afb64',
    messagingSenderId: '224930641005',
    projectId: 'bingio-flutter',
    storageBucket: 'bingio-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: GoogleFirebaseApiKeys.ios,
    appId: '1:224930641005:ios:8e61d5cdef8c54f91afb64',
    messagingSenderId: '224930641005',
    projectId: 'bingio-flutter',
    storageBucket: 'bingio-flutter.firebasestorage.app',
    androidClientId: '224930641005-m4hb7s2r58lb5ep3enbmuv8rdq30ulsl.apps.googleusercontent.com',
    iosClientId: '224930641005-ted7ebvri88dl1a5edehqcspcf9cm31e.apps.googleusercontent.com',
    iosBundleId: 'com.dalbrar.bingio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: GoogleFirebaseApiKeys.macos,
    appId: '1:224930641005:ios:8e61d5cdef8c54f91afb64',
    messagingSenderId: '224930641005',
    projectId: 'bingio-flutter',
    storageBucket: 'bingio-flutter.firebasestorage.app',
    androidClientId: '224930641005-m4hb7s2r58lb5ep3enbmuv8rdq30ulsl.apps.googleusercontent.com',
    iosClientId: '224930641005-ted7ebvri88dl1a5edehqcspcf9cm31e.apps.googleusercontent.com',
    iosBundleId: 'com.dalbrar.bingio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: GoogleFirebaseApiKeys.windows,
    appId: '1:224930641005:web:2d0f759770bb79861afb64',
    messagingSenderId: '224930641005',
    projectId: 'bingio-flutter',
    authDomain: 'bingio-flutter.firebaseapp.com',
    storageBucket: 'bingio-flutter.firebasestorage.app',
  );

}